### ISSUE TITLE
Overview of Page Templates

### ISSUE THREAD

**Issue by paaljoachim** [BinaryMoon/jarvis#12]
Hey

I took a look at the Page Attributes -> Templates and noticed a few.
It would be great if you could add some notes to the readme about each template. Name and what they do. As it would be easier to get an overview of what the theme contains.
Thanks.

**Comment by BinaryMoon** [comment]
Thanks - that's a good idea and I really appreciate the feedback!

On a slightly related note - what do you think of page templates now that we have Gutenberg? Are they still needed if you can add custom features to any page anyway?

I am wondering about removing some/ all of the page templates as I think their use is less relevant now. But then I am not everyone so I wonder if other people would still find them useful. What do you think?

Thanks

**Comment by paaljoachim** [comment]
Hey Ben

Page templates are needed. For now anyway and likely another 6 or so months until Gutenberg has a way to save templates (kinda like saving reusable blocks). In the mean time it would be good to add page templates in the existing fashion so to speak.

If you can write a bit about the page templates you have made then I can also figure out how to test them out and give you feedback directly on those.

**Comment by paaljoachim** [comment]
Inspiration.
The newest theme from Anders Noren: https://wordpress.org/themes/chaplin/
Uses a Cover template that has a image behind the title and using the excerpt also adds some text below it. Take a look I believe it can bring up some thoughts.

Btw
"Expanding the Editor outside of post_content"
https://github.com/WordPress/gutenberg/issues/16281
It is just a matter of time before the Title becomes a block making it possible to add the title to the cover block.

**Comment by BinaryMoon** [comment]
Thanks - that makes use.

I've updated the readme.txt to include descriptions of the templates, and made a couple of template based changes.

Keep in mind that I haven't tested these templates yet. They probably don't work 100% - I'm still focused on getting the theme design to look right. I'll go through and fix stuff once the theme looks nice :)

**Comment by BinaryMoon** [comment]
Hey @paaljoachim are the changes I made ok or would you like to see something else?

**Comment by paaljoachim** [comment]
Hey Ben..:)

Going through the page templates.
Content only. 
Shows "A template that removes the site header and footer and displays just the page content." It also removes the background color. This seems ready to be used for a page builder like Beaver Builder or Elementor or other page builders that will control the full page.

<img width="1313" alt="Screen Shot 2019-07-19 at 16 58 34" src="https://user-images.githubusercontent.com/5323259/61544819-78a4a700-aa46-11e9-9c7c-5a6ebce94f97.png">


Contributors. Shows the background color selected through the customizer.
Looks totally fine. Might be useful.

<img width="840" alt="Screen Shot 2019-07-19 at 17 00 27" src="https://user-images.githubusercontent.com/5323259/61544972-bdc8d900-aa46-11e9-8c9b-9b4692e0156d.png">

Child Page Grid.  Kinda shows sub pages like a blog page shows blog posts.
Looks ok. Might be useful.

<img width="907" alt="Screen Shot 2019-07-19 at 16 59 40" src="https://user-images.githubusercontent.com/5323259/61544901-9e31b080-aa46-11e9-9da8-015a08202c91.png">

Portfolio. Not checked.

I would just leave all of them in as they are (for now anyway).
