### ISSUE TITLE
Customizer Theme Options

### ISSUE THREAD

**Issue by paaljoachim** [BinaryMoon/jarvis#25]
In the customizer there is the Theme Options section with the following alternatives.

"Display Category Summaries"
"Display Date and Social Links in Header"
"Autoplay the Featured Content Slider"

I do not know yet what these do. Is this not active yet? For the moment they just seem like placeholders.

**Comment by BinaryMoon** [comment]
I will probably delete these. They are left over from my starter theme - I keep a few controls in there so I can copy and paste things to get started more quickly.

**Comment by paaljoachim** [comment]
I am thinking we will also down the line find out if some controls will end up there. So for now it seems like a good place to just keep placeholders.

**Comment by BinaryMoon** [comment]
I've removed these now :)

**Comment by paaljoachim** [comment]
Yeah. I noticed.
It will be interesting to see what else ends up in the customizer..:)
