### ISSUE TITLE
Testing out the speed of various themes

### ISSUE THREAD

**Issue by paaljoachim** [BinaryMoon/jarvis#37]
I am looking to renew an existing client site: https://celias.no/ 
Today is uses Avada and I am looking into a slimmer and speedier theme. I made the test site https://fragmentsofawalk.com and found various themes I wanted to test out with focus on speed.

## Testing themes

Following plugins are active:
Akismet, All in One WP Security, Caldera Forms, Companion Auto Update, Content Aware Sidebars, Custom Feeds for Instagram, Duplicator Pro, Elementor, FileBird Lite, Kadence Toolkit, PageSpeed Ninja, WooCommerce and WooCommerce Stripe Gateway.

https://tools.pingdom.com/

San Fransisco (as it is close to the data center for Arch Hosting where I have my domains.)

Overlay theme:
Score 90
Page size: 771.6 KB
Load time: 2.02 s / 514 ms / 596 ms (Ran the test multiple times)
Requests: 55
https://overlaywp.com/

Guten theme:
Score 90
Page size: 886.7 KB
Load time: 1.82 s
Requests: 55
https://gutentheme.org/

Pagebuilder framework theme (By David Vongries):
Score 90
Page size: 771.5 KB
Load time: 1.47 s  / 1.33 s
Requests: 55
https://wp-pagebuilderframework.com/

ZenEther theme:
Score 90
Page size: 874.8 KB
Load time: 1.56 s
Requests: 55
https://zentemplates.com/

Chaplin theme:
Score 90
Page size: 879.36 KB
Load time: 2.31 s
Requests: 62
https://andersnoren.se/themes/chaplin/

Primer theme:
Score 89
Page size: 837.6 KB
Load time: 1.70 s
Requests: 60
https://github.com/godaddy/wp-primer-theme

Tabor theme (By Rich Tabor):
Score 90
Page size: 953.4 KB
Load time: 2.41 s
Requests: 42
https://themebeans.com/themes/tabor/

Twenty Nineteen theme:
Score 90
Page size: 784.8 KB
Load time: 2.01 s
Requests: 52

Jarvis theme (as of 25 July 2019):
Score 90
Page size: 784.8 KB
Load time: 2.01 s
Requests: 52

Gutenwp theme:
Score 89
Page size: 1.2 MB
Load time: 1.41 s
Requests: 68
https://www.themeum.com/product/gutenwp/

Atomic Block theme:
Score 89
Page size: 872.6 KB
Load time: 1.29 s
Requests: 64
https://atomicblocks.com/

OceanWP theme:
Score 89
Page size: 887 KB
Load time: 2.02 s
Requests: 55
https://oceanwp.org/

Ascend theme:
Score 90
Page size: 1.2 MB
Load time: 1.95 s
Requests: 78
https://www.kadencethemes.com/

Neve theme:
Score 90
Page size: 801.3 KB
Load time: 1.79 s
Requests: 53
https://themeisle.com/themes/neve/

Zakra theme:
Score 90
Page size: 778.2 KB
Load time: 1.36 s
Requests: 53
https://themegrill.com/wordpress-themes/

Beans theme (Thierry Muller):
Score 90
Page size: 866.2 KB
Load time: 1.91 s
Requests: 53
https://www.getbeans.io/

**Comment by BinaryMoon** [comment]
Hey Paal - thanks for the research. It's interesting to see just how much stuff gets added by plugins.

I tested my Jarvis test site and it got a better score than anything you're seeing here, but that's because it's not including all the bits from those plugins.

<img width="825" alt="Screenshot 2019-07-25 at 21 20 11" src="https://user-images.githubusercontent.com/1004130/61905963-3685d480-af22-11e9-841e-d3b594f22aae.png">

The results I get are here if you're interested.
https://tools.pingdom.com/#5b0ab27c99800000

Perhaps it would be worth reviewing what plugins you have as well? Maybe there's some that are less popular, but more performant? It could potentially make more difference than the theme I think.

**Comment by paaljoachim** [comment]
Hey Ben

I turned off all the plugins. Installed the latest version of Jarvis. Then tested in pingdom.
I also tested a few other themes as well.

Jarvis:
A 92
Page Size: 28.4 KB
Load time: 329 ms
Requests: 7

Overlay:
B 82
Page Size: 158 KB
Load time: 390 ms
Requests: 20

Chaplin:
B 87
Page Size: 115 KB
Load time: 400 ms
Requests: 12

Guten:
B 83
Page Size: 266.3 KB
Load time: 414 ms
Requests: 23

Beans:
B 88
Page Size: 156.4 KB
Load time: 416 ms
Requests: 10

Page Builder Framework:
B 86
Page Size: 64.8 KB
Load time: 391 ms
Requests: 13

Tabor:
B 83
Page Size: 241.8 KB
Load time: 425 ms
Requests: 21

Atomic Blocks:
B 84
Page Size: 158.3 KB
Load time: 361 ms
Requests: 16

Jarvis is sure doing well in these tests!

> Perhaps it would be worth reviewing what plugins you have as well? Maybe there's some that are less popular, but more performant? 

How are you thinking we should do this? It would be great to review the plugins.

**Comment by BinaryMoon** [comment]
Well those scores are a lot nicer (for me :))

> How are you thinking we should do this? It would be great to review the plugins.

I don't think that's something I can do. It depends on your requirements for your projects. Personally I would try to measure the weight of the plugins individually, and see which are adding the most stuff, and then replace them with something lighter.

I don't know your requirements but I would guess many of the plugins do a lot of things that you don't use.

For example the theme you currently have activated looks to be one of the bigger themes. I ran the [pingdom test](https://tools.pingdom.com/#5b0cc94e91c00000) and sorted the file requests by response body size descending (untick the rising box) and then you can see the biggest requests.

The top one is font-awesome.ttf. The theme is including the entire font-awesome library, but I suspect it's only using a few icons.

If you enable all your plugins then you could run the test again, see what plugin is using the largest files and then see if you can replace it with something more efficient.
