### ISSUE TITLE
Footer widgets show max 3 in a row

### ISSUE THREAD

**Issue by paaljoachim** [BinaryMoon/jarvis#39]
Hey

I noticed this text in the customizer:
"Widgets that display at the bottom of your website. They are arranged in 4 columns and lined up automatically to make the best use of the space available."

I added 4 widgets and it now shows up like this:

![Screen Shot 2019-07-27 at 22 25 01](https://user-images.githubusercontent.com/5323259/61999266-6fa67c00-b0bd-11e9-9605-9de76ed4ca52.png)

3 widgets in a row and the 4th widget below.

**Comment by BinaryMoon** [comment]
Oops :)

The description is from my starter theme and I didn't update it.
