### ISSUE TITLE
More control over the Search Icon

### ISSUE THREAD

**Issue by paaljoachim** [BinaryMoon/jarvis#51]
I notice that the Search icon is automatically added in the top right corner of the page.
It would be nice to have a display Search icon checkbox in the customizer to where the user can select to turn it on or off.

**Comment by BinaryMoon** [comment]
I've added some info about hiding this to the docs. Hopefully that's enough.
https://github.com/BinaryMoon/jarvis/wiki/Header

**Comment by paaljoachim** [comment]
That might be ok.

**Comment by paaljoachim** [comment]
The reason why I say so is that people who want to remove it and look for the customizer option might be puzzled in how to do remove it.
