### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by paaljoachim** [BinaryMoon/jarvis#7]
Hey

I downloaded and installed the jarvis theme on a local site using Desktop Server and Chrome.
On Mac OSX 10.13.6.

Theme activated. On frontend I clicked one of the pages I added to the menu and received the following Fatal error code:

Fatal error: Uncaught Error: Call to undefined function jarvis_breadcrumbs() in /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-content/themes/jarvis-master/parts/content-single-page.php:28 Stack trace: #0 /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-includes/template.php(724): require() #1 /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-includes/template.php(671): load_template('/Users/paaljoac...', false) #2 /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-includes/general-template.php(168): locate_template(Array, true, false) #3 /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-content/themes/jarvis-master/singular.php(31): get_template_part('parts/content-s...', 'page') #4 /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-includes/template-loader.php(78): include('/Users/paaljoac...') #5 /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-blog-header.php(19): require_once('/Users in /Users/paaljoachimromdahl/Documents/Websites/test-may-2019.dev.cc/wp-content/themes/jarvis-master/parts/content-single-page.php on line 28

![Screen Shot 2019-07-10 at 01 53 57](https://user-images.githubusercontent.com/5323259/60930398-9c812380-a2b5-11e9-8782-c6a656d321fa.png)

**Comment by BinaryMoon** [comment]
Thanks a lot for the report - I've fixed this now!
